version: '3'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./confs/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db/mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "5001:80"
    depends_on:
      - db

  alembic:
    build:
      context: .
    env_file:
      - .env
    command: alembic upgrade head
    environment:
      - ALEMBIC_CONFIG=./alembic.ini
    volumes:
      - .:/app
    depends_on:
      - db
