"""update dalle image_url.

Revision ID: 3368bf3a0b0a
Revises: 3d7d9e74d35d
Create Date: 2023-12-19 15:09:46.178705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3368bf3a0b0a'
down_revision = '3d7d9e74d35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dalle', 'image_url',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dalle', 'image_url',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
