"""add functions.

Revision ID: c2ccea22ba70
Revises: 3368bf3a0b0a
Create Date: 2023-12-21 15:39:57.613642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2ccea22ba70'
down_revision = '3368bf3a0b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True, comment='名称'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='参数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functions_id'), 'functions', ['id'], unique=False)
    op.drop_index('ix_dalle_id', table_name='dalle')
    op.drop_table('dalle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dalle',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('prompt', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('n', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('log_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dalle_id', 'dalle', ['id'], unique=False)
    op.drop_index(op.f('ix_functions_id'), table_name='functions')
    op.drop_table('functions')
    # ### end Alembic commands ###
