"""add dalle.

Revision ID: e350de9f32a7
Revises: d34dc153a337
Create Date: 2023-12-19 14:35:21.930531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e350de9f32a7'
down_revision = 'd34dc153a337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('prompt', sa.String(length=200), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=200), nullable=True),
    sa.Column('log_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dalle_id'), 'dalle', ['id'], unique=False)
    op.create_index(op.f('ix_dalle_name'), 'dalle', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dalle_name'), table_name='dalle')
    op.drop_index(op.f('ix_dalle_id'), table_name='dalle')
    op.drop_table('dalle')
    # ### end Alembic commands ###
