"""update dalle.

Revision ID: fb32cb00c20d
Revises: e350de9f32a7
Create Date: 2023-12-19 14:39:08.806963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb32cb00c20d'
down_revision = 'e350de9f32a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dalle_name', table_name='dalle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dalle_name', 'dalle', ['name'], unique=False)
    # ### end Alembic commands ###
