name: Publish fb-hook docker image
permissions: {}
on:
  push:
    branches: [ "dev" ]
    paths:
      - custom-go/go.mod
      - custom-go/go.sum
      - .gitea/workflows/build-fb-hook.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Log in to Docker Hub
        uses: https://git.fireboom.io/docker/login-action@v3
        with:
          registry: ${{ vars.HARBOR_REPO_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and push
        uses: https://git.fireboom.io/docker/build-push-action@v5
        with:
          context: .
          file: fb-hook.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ vars.HARBOR_REPO_URL }}/${{ vars.HARBOR_ORG_NAME }}/${{ vars.HARBOR_REPO_NAME }}-fb-hook:${{ env.DATE }}
            ${{ vars.HARBOR_REPO_URL }}/${{ vars.HARBOR_ORG_NAME }}/${{ vars.HARBOR_REPO_NAME }}-fb-hook:latest
      - uses: https://git.fireboom.io/fireboomio/kubectl-action@v2.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/${{ vars.KUBE_DEPLOYMENT }} -n ${{ vars.KUBE_NAMESPACE }} ${{ vars.KUBE_CONTAINER_NAME }}=${{ vars.HARBOR_REPO_URL }}/${{ vars.HARBOR_ORG_NAME }}/${{ vars.HARBOR_REPO_NAME }}-fb-hook:${{ env.DATE }}
